// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequirementImpactAssistant.Web.Data;

#nullable disable

namespace RequirementImpactAssistant.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614165245_AddRetrievedContextItemsPersistence")]
    partial class AddRetrievedContextItemsPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.AiAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("AiAnalysisResults", (string)null);
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FixedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectRequest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SituationDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Analyses", (string)null);
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ContextFragment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("ContextFragments", (string)null);
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertConclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConclusionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FixedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("ExpertConclusions", (string)null);
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExpertEvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpertEvaluationId");

                    b.ToTable("ExpertCorrections", (string)null);
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertEvaluatedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExpertEvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpertEvaluationId");

                    b.ToTable("ExpertEvaluatedItems", (string)null);
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextSufficiency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultUsefulness")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("ExpertEvaluations", (string)null);
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertMissedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExpertEvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpertEvaluationId");

                    b.ToTable("ExpertMissedItems", (string)null);
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.AiAnalysisResult", b =>
                {
                    b.HasOne("RequirementImpactAssistant.Web.Domain.Analysis", null)
                        .WithOne("AiAnalysisResult")
                        .HasForeignKey("RequirementImpactAssistant.Web.Domain.AiAnalysisResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RequirementImpactAssistant.Web.Domain.AiAnalysisResultMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("AiAnalysisResultId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AdapterName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("MetadataAdapterName");

                            b1.Property<string>("AnalysisMode")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("DirectLlm")
                                .HasColumnName("AnalysisMode");

                            b1.Property<string>("EngineName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("MetadataEngineName");

                            b1.Property<bool>("ManualContextForwardedToExternalAiOrRag")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false)
                                .HasColumnName("ManualContextForwardedToExternalAiOrRag");

                            b1.Property<string>("ModelWorkflowProfileName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("MetadataModelWorkflowProfileName");

                            b1.Property<string>("ProviderName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("MetadataProviderName");

                            b1.Property<string>("RetrievedContextState")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("Unavailable")
                                .HasColumnName("RetrievedContextState");

                            b1.Property<string>("Warnings")
                                .HasColumnType("TEXT")
                                .HasColumnName("Warnings");

                            b1.HasKey("AiAnalysisResultId");

                            b1.ToTable("AiAnalysisResults");

                            b1.WithOwner()
                                .HasForeignKey("AiAnalysisResultId");

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.RetrievedContextItem", "RetrievedContextItems", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("AdapterName")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Completeness")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Excerpt")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ExternalReference")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("FragmentId")
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ProviderName")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.Property<int?>("Rank")
                                        .HasColumnType("INTEGER");

                                    b2.Property<double?>("Score")
                                        .HasColumnType("REAL");

                                    b2.Property<string>("SourceId")
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("SourceTitle")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("UrlOrReference")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("WarningOrLimitationNote")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Ordinal");

                                    b2.ToTable("RetrievedContextItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.Navigation("RetrievedContextItems");
                        });

                    b.OwnsOne("RequirementImpactAssistant.Web.Domain.Impact.ImpactMap", "ImpactMap", b1 =>
                        {
                            b1.Property<Guid>("AiAnalysisResultId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AiAnalysisResultId");

                            b1.ToTable("ImpactMaps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AiAnalysisResultId");

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "AffectedApiInterfacesDocumentsTests", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapAffectedApiInterfacesDocumentsTests", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "AffectedArchitecturalConstraints", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapAffectedArchitecturalConstraints", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "AffectedOrganizationalContextItems", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapAffectedOrganizationalContextItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "AffectedProjectDecisions", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapAffectedProjectDecisions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "AffectedRequirements", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapAffectedRequirements", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "AffectedTasks", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapAffectedTasks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "ClarificationQuestions", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapClarificationQuestions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "Contradictions", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapContradictions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "MissingInformation", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapMissingInformation", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "OptionsForExpertReview", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapOptionsForExpertReview", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsMany("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "Risks", b2 =>
                                {
                                    b2.Property<Guid>("AiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AiAnalysisResultId", "Id");

                                    b2.ToTable("ImpactMapRisks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AiAnalysisResultId");
                                });

                            b1.OwnsOne("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "ChangeSummary", b2 =>
                                {
                                    b2.Property<Guid>("ImpactMapAiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ChangeSummaryDescription");

                                    b2.Property<string>("Id")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ChangeSummaryId");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ChangeSummaryItemType");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ChangeSummaryNotes");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ChangeSummaryRelatedContextFragmentIds");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ChangeSummarySeverity");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ChangeSummaryTitle");

                                    b2.HasKey("ImpactMapAiAnalysisResultId");

                                    b2.ToTable("ImpactMaps");

                                    b2.WithOwner()
                                        .HasForeignKey("ImpactMapAiAnalysisResultId");
                                });

                            b1.OwnsOne("RequirementImpactAssistant.Web.Domain.Impact.ImpactMapItem", "PreliminaryAssessment", b2 =>
                                {
                                    b2.Property<Guid>("ImpactMapAiAnalysisResultId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PreliminaryAssessmentDescription");

                                    b2.Property<string>("Id")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PreliminaryAssessmentId");

                                    b2.Property<string>("ItemType")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PreliminaryAssessmentItemType");

                                    b2.Property<string>("Notes")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PreliminaryAssessmentNotes");

                                    b2.Property<string>("RelatedContextFragmentIds")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PreliminaryAssessmentRelatedContextFragmentIds");

                                    b2.Property<string>("Severity")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PreliminaryAssessmentSeverity");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("PreliminaryAssessmentTitle");

                                    b2.HasKey("ImpactMapAiAnalysisResultId");

                                    b2.ToTable("ImpactMaps");

                                    b2.WithOwner()
                                        .HasForeignKey("ImpactMapAiAnalysisResultId");
                                });

                            b1.Navigation("AffectedApiInterfacesDocumentsTests");

                            b1.Navigation("AffectedArchitecturalConstraints");

                            b1.Navigation("AffectedOrganizationalContextItems");

                            b1.Navigation("AffectedProjectDecisions");

                            b1.Navigation("AffectedRequirements");

                            b1.Navigation("AffectedTasks");

                            b1.Navigation("ChangeSummary")
                                .IsRequired();

                            b1.Navigation("ClarificationQuestions");

                            b1.Navigation("Contradictions");

                            b1.Navigation("MissingInformation");

                            b1.Navigation("OptionsForExpertReview");

                            b1.Navigation("PreliminaryAssessment")
                                .IsRequired();

                            b1.Navigation("Risks");
                        });

                    b.Navigation("ImpactMap");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ContextFragment", b =>
                {
                    b.HasOne("RequirementImpactAssistant.Web.Domain.Analysis", null)
                        .WithMany("ContextFragments")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertConclusion", b =>
                {
                    b.HasOne("RequirementImpactAssistant.Web.Domain.Analysis", null)
                        .WithOne("ExpertConclusion")
                        .HasForeignKey("RequirementImpactAssistant.Web.Domain.ExpertConclusion", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertCorrection", b =>
                {
                    b.HasOne("RequirementImpactAssistant.Web.Domain.ExpertEvaluation", null)
                        .WithMany("Corrections")
                        .HasForeignKey("ExpertEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertEvaluatedItem", b =>
                {
                    b.HasOne("RequirementImpactAssistant.Web.Domain.ExpertEvaluation", null)
                        .WithMany("EvaluatedItems")
                        .HasForeignKey("ExpertEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertEvaluation", b =>
                {
                    b.HasOne("RequirementImpactAssistant.Web.Domain.Analysis", null)
                        .WithOne("ExpertEvaluation")
                        .HasForeignKey("RequirementImpactAssistant.Web.Domain.ExpertEvaluation", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertMissedItem", b =>
                {
                    b.HasOne("RequirementImpactAssistant.Web.Domain.ExpertEvaluation", null)
                        .WithMany("MissedItems")
                        .HasForeignKey("ExpertEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.Analysis", b =>
                {
                    b.Navigation("AiAnalysisResult");

                    b.Navigation("ContextFragments");

                    b.Navigation("ExpertConclusion");

                    b.Navigation("ExpertEvaluation");
                });

            modelBuilder.Entity("RequirementImpactAssistant.Web.Domain.ExpertEvaluation", b =>
                {
                    b.Navigation("Corrections");

                    b.Navigation("EvaluatedItems");

                    b.Navigation("MissedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
