using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using RequirementImpactAssistant.Web.Domain.Impact;

namespace RequirementImpactAssistant.Web.Application.Analysis.Llm;

public sealed class DemoLlmProvider : ILlmProvider
{
    public Task<LlmProviderResponse> CompleteAsync(
        LlmProviderRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        cancellationToken.ThrowIfCancellationRequested();

        var fingerprint = CreateFingerprint(request);
        var impactMap = CreateImpactMap(request, fingerprint);
        var rawResponse = CreateRawResponse(request, fingerprint);

        return Task.FromResult(new LlmProviderResponse(
            LlmProviderResponseStatus.Succeeded,
            impactMap,
            rawResponse,
            []));
    }

    private static ImpactMap CreateImpactMap(LlmProviderRequest request, string fingerprint)
    {
        var analysis = request.AnalysisRequest.InputSnapshot.Analysis;
        var fragment = request.AnalysisRequest.InputSnapshot.ContextFragments.FirstOrDefault();
        var sourceLabel = string.IsNullOrWhiteSpace(fragment?.Source)
            ? "provided project context"
            : fragment.Source;

        var impactMap = new ImpactMap
        {
            ChangeSummary =
            {
                Title = CreateTitle("Demo impact summary", analysis.Title),
                Description = $"Deterministic local analysis for request {fingerprint}: {CreateSummary(analysis.ProjectRequest)}",
                Severity = ImpactSeverity.Medium,
                Notes = "Generated by the local demo provider without external network calls."
            },
            PreliminaryAssessment =
            {
                Title = "Requires human expert review",
                Description = "The generated material is preliminary and should be checked by a project expert before any management action.",
                Severity = ImpactSeverity.Medium,
                Notes = $"Demo provider fingerprint: {fingerprint}."
            }
        };

        var requirement = impactMap.AddAffectedRequirement();
        requirement.Title = "Requirement scope may need clarification";
        requirement.Description = CreateSummary(analysis.OriginalDescription);
        requirement.Severity = ImpactSeverity.Medium;
        AddRelatedContext(requirement, fragment?.Id);

        var task = impactMap.AddAffectedTask();
        task.Title = "Implementation task review";
        task.Description = $"Check planned work against {sourceLabel}.";
        task.Severity = ImpactSeverity.Low;
        AddRelatedContext(task, fragment?.Id);

        var risk = impactMap.AddRisk();
        risk.Title = "Unvalidated downstream impact";
        risk.Description = "Some affected modules or documents may be missing until the expert completes review.";
        risk.Severity = ImpactSeverity.Medium;
        AddRelatedContext(risk, fragment?.Id);

        var question = impactMap.AddClarificationQuestion();
        question.Title = "Confirm acceptance criteria";
        question.Description = "Which acceptance criteria must change for this request?";
        question.Severity = ImpactSeverity.Low;
        AddRelatedContext(question, fragment?.Id);

        var option = impactMap.AddOptionForExpertReview();
        option.Title = "Review before implementation planning";
        option.Description = "Use this draft as an input for expert assessment, not as an approved decision.";
        option.Severity = ImpactSeverity.Low;

        return impactMap;
    }

    private static string CreateRawResponse(LlmProviderRequest request, string fingerprint)
    {
        var payload = new
        {
            provider = LlmProviderNames.Demo,
            status = "success",
            fingerprint,
            analysisTitle = request.AnalysisRequest.InputSnapshot.Analysis.Title,
            message = "Deterministic local demo response. No external provider, network, SDK, or secret is used."
        };

        return JsonSerializer.Serialize(payload);
    }

    private static string CreateFingerprint(LlmProviderRequest request)
    {
        var source = string.Join(
            "\n",
            request.Provider,
            request.Prompt,
            request.AnalysisRequest.InputSnapshotJson);
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(source));

        return Convert.ToHexString(hash)[..12].ToLowerInvariant();
    }

    private static string CreateTitle(string fallback, string value) =>
        string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();

    private static string CreateSummary(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "No detailed text was provided in the request.";
        }

        var normalized = string.Join(' ', value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));

        return normalized.Length <= 180 ? normalized : $"{normalized[..177]}...";
    }

    private static void AddRelatedContext(ImpactMapItem item, Guid? contextFragmentId)
    {
        if (contextFragmentId.HasValue)
        {
            item.RelatedContextFragmentIds.Add(contextFragmentId.Value);
        }
    }
}
